##############################################################
## This is just a basic config file to get the app to start ##
##############################################################

authentication:
  username: hotio
  password: PASSWORD

port: 3030

triggers:
  sonarr:
    - name: sonarr
