##############################################################
## This is just a basic config file to get the app to start ##
##############################################################

port: 3030

triggers:
  sonarr:
    - name: sonarr
